resources:
- ingress-nginx.yml
images:
- name: registry.k8s.io/ingress-nginx/kube-webhook-certgen
  newName: jrrickard/kube-webhook-certgen
- name: registry.k8s.io/ingress-nginx/controller
  newName: jrrickard/controller

